  "chroma",
  "djlint",
  "frontmatter",
  "gofumpt",
  "gohugoio",
  "hugo",
  "jakebailey",
  "lighthouse",
  "malva",
  "nodejs",
  "permalink",
  "pipx",
  "puppeteer",
  "scms",
  "shortcode",
  "shortcodes",
  "unreviewed",
