---
miseDeps:
  helmcharts:
    - slug: helm
      answerKey: helm_version
      tomlKey: helm
      kind: githubrelease
      owner: helm
      repo: helm
      trimPrefix: true
      file: .mise/conf.d/30-helmcharts.toml
    - slug: helmUnittest
      answerKey: helm_unittest_version
      tomlKey: helm_unittest_version
      kind: githubrelease
      owner: helm-unittest
      repo: helm-unittest
      trimPrefix: true
      file: .mise/conf.d/30-helmcharts.toml
