# The answers the Boilerplate templates were applied with, and the template
# version they were rendered from. Rewritten by "mise run update-templates".
---
template_url: .
template_ref: main
devcontainer: true
github_owner: aacebedo
layers: ""
license: Apache-2.0
project_description: Stackable Boilerplate templates
project_name: boilerplate-templates
project_slug: boilerplate-templates
