dictionaries = ["en_us"]

words = [
  "aacebedo",
  "actionid",
  "aquasecurity",
  "autodiscover",
  "autodiscovered",
  "autodiscovery",
  "autoqueue",
  "biomejs",
  "blopker",
  "captureindex",
  "cjs",
  "cli",
  "cocogitto",
  "codebook",
  "commitizen",
  "commitmessage",
  "commitusingapi",
  "boilerplate",
  "cron",
  "devcontainer",
  "devcontaineruser",
  "dprint",
  "dotfiles",
  "editorconfig",
  "findsubmatch",
  "fmt",
  "githubrelease",
  "groupby",
  "gruntwork",
  "hidecredit",
  "jdx",
  "koalaman",
  "linters",
  "matchpattern",
  "mergify",
  "mikefarah",
  "misconfig",
  "mise",
  "mise's",
  "mkdir",
  "mvdan",
  "owenlamont",
  "pep440",
  "pipefail",
  "pipx",
  "prek",
  "pullrequest",
  "pypi",
  "replacepattern",
  "rumdl",
  "rvben",
  "ryl",
  "scmid",
  "scms",
  "scop",
  "sed",
  "shellcheck",
  "shfmt",
  "sourceid",
  "tombi",
  "trimprefix",
  "trivy",
  "updatecli",
  "venv",
  "versionfilter",
  "wasm",
  "yamllint",
  "yamllint's",
{{ template "fragments" (dict "vars" . "name" "codebook-words.toml") }}]

ignore_paths = [
  ".boilerplate-answers.yaml",
  "CHANGELOG.md",
  "cog.toml",
  ".git/**",
  "REUSE.toml",
]
