[tools]
shellcheck = "0.11.0"
"github:editorconfig-checker/editorconfig-checker" = "4.0.2"
trivy = "0.75.0"
"github:owenlamont/ryl" = "0.24.0"
prek = "0.5.5"
shfmt = "3.14.1"
dprint = "0.60.1"
"github:tombi-toml/tombi" = "1.7.2"
"github:cocogitto/cocogitto" = "7.0.0"
gh = "2.102.0"
rumdl = "0.2.77"
updatecli = "0.122.1"
biome = "2.5.15"
"github:blopker/codebook" = "0.3.42"
uv = "0.12.23"
"pipx:reuse" = { version = "6.2.0", extras = "charset-normalizer" }
boilerplate = "0.16.0"
yq = "4.54.1"

[vars]
# editorconfig-checker-disable
repo_host = '''{{ exec(command="git remote get-url origin 2>/dev/null |
  sed 's/[.]git$//' |
  awk -F'[/:]' '{print $(NF-2)}' |
  sed 's/.*@//' || echo ''") | trim }}'''
repo_owner = '''{{ exec(command="git remote get-url origin 2>/dev/null |
  sed 's/[.]git$//' |
  awk -F'[/:]' '{print $(NF-1)}' || echo ''") | trim }}'''
repo_name = '''{{ exec(command="git remote get-url origin 2>/dev/null |
  sed 's/[.]git$//' |
  awk -F'[/:]' '{print $NF}' || echo ''") | trim }}'''
# editorconfig-checker-enable
repo_url = "https://{{vars.repo_host}}/{{vars.repo_owner}}/{{vars.repo_name}}"
commit_sha = '''{{ exec(command="git rev-parse HEAD 2>/dev/null || echo ''") | trim }}'''

[bootstrap.packages]
"apt:bash" = "latest"
"apt:git" = "latest"
