
[[repos]]
repo = "local"

[[repos.hooks]]
id = "cargo-fmt"
name = "cargo fmt"
entry = "cargo fmt --"
language = "system"
types = ["rust"]

[[repos]]
repo = "local"

[[repos.hooks]]
id = "cargo-clippy"
name = "cargo clippy"
entry = "cargo clippy --all-targets -- -D warnings"
language = "system"
types = ["rust"]
pass_filenames = false

[[repos]]
repo = "local"

[[repos.hooks]]
id = "cargo-check"
name = "cargo check"
entry = "cargo check --all-targets"
language = "system"
types = ["rust"]
pass_filenames = false
