{{- range $i, $dep := .dockerfileDeps }}
{{- if $i }}
---
{{- end }}
name: "Bump {{ $dep.arg }} in {{ $dep.file }}"

scms:
  default:
    kind: github
    spec:
      owner: "{{ $.github.owner }}"
      repository: "{{ $.github.repository }}"
      token: '{{ requiredEnv "UPDATECLI_GITHUB_TOKEN" }}'
      branch: "{{ $.github.branch }}"
      commitusingapi: true
      commitmessage:
        type: chore
        scope: deps
        hidecredit: true

sources:
  {{ $dep.slug }}:
    kind: {{ $dep.kind }}
  {{- if eq $dep.kind "dockerimage" }}
    name: "Get latest {{ $dep.image }} tag"
    spec:
      image: {{ $dep.image }}
      tagfilter: '{{ $dep.tagfilter }}'
      versionfilter:
        kind: semver
  {{- else }}
    name: "Get latest {{ $dep.owner }}/{{ $dep.repo }} release"
    spec:
      owner: {{ $dep.owner }}
      repository: {{ $dep.repo }}
      token: '{{ requiredEnv "UPDATECLI_GITHUB_TOKEN" }}'
      versionfilter:
        kind: semver
  {{- if $dep.trimPrefix }}
    transformers:
      - trimprefix: "v"
  {{- end }}
  {{- end }}

targets:
  {{ $dep.slug }}:
    name: "Update {{ $dep.arg }} in {{ $dep.file }}"
    kind: dockerfile
    scmid: default
    sourceid: {{ $dep.slug }}
    spec:
      file: {{ $dep.file }}
      instruction:
        keyword: ARG
        matcher: {{ $dep.arg }}

actions:
  default:
    kind: github/pullrequest
    scmid: default
    title: 'chore(deps): bump {{ $dep.arg }} to {{ "{{" }} source "{{ $dep.slug }}" {{ "}}" }}'
    spec:
      labels:
        - dependencies
{{- end }}
