---
name: PR

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  pr-checks:
    uses: {{ shell "sh" (printf "%s/_partials/static-files.sh" templateFolder) (env "PWD" "") .layers "github" "reusable-pr-checks.yaml" }}
    permissions:
      contents: read
      packages: read
    with:
{{- if .devcontainer }}
      container-image: ghcr.io/aacebedo/devcontainer-base:{{ .devcontainer_image_version }}
      container-options: >-
        --user root
{{ template "fragments" (dict "vars" . "name" "job-container-options.yaml") }}
{{- end }}
      extra-tasks: >-
{{ template "fragments" (dict "vars" . "name" "pr-extra-tasks.yaml") -}}
