---
name: Release

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main

permissions: {}

jobs:
  release:
    uses: {{ shell "sh" (printf "%s/_partials/static-files.sh" templateFolder) (env "PWD" "") .layers "github" "reusable-release.yaml" }}
    permissions:
      contents: write
{{ template "fragments" (dict "vars" . "name" "release-job-permissions.yaml") -}}
{{- if .devcontainer }}
    with:
      container-image: ghcr.io/aacebedo/devcontainer-base:{{ .devcontainer_image_version }}
      container-options: >-
        --user root
{{ template "fragments" (dict "vars" . "name" "job-container-options.yaml") }}
{{- end -}}
