---
name: Update dependencies

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 1"

permissions: {}

jobs:
  update-deps:
    uses: {{ shell "sh" (printf "%s/_partials/static-files.sh" templateFolder) (env "PWD" "") .layers "github" "reusable-update-deps.yaml" }}
    permissions:
      contents: read
    secrets: inherit
