---
name: Release

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main

permissions: {}

jobs:
  release:
    uses: ./.github/workflows/reusable-release.yaml
    secrets: inherit
    permissions:
      contents: write

    with:
      container-image: ghcr.io/aacebedo/devcontainer-base:1.24.1
      container-options: >-
        --user root
